-- Backfill migration for core tables that exist in DB but were missing from migrations

-- 1. storage_units
CREATE TABLE IF NOT EXISTS public.storage_units (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_number text NOT NULL,
    facility text,
    unit_type text,
    size text,
    price numeric,
    bond numeric,
    access_hours text,
    status text DEFAULT 'Available' CHECK (status IN ('Available', 'Submitted', 'Unavailable')),
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);
ALTER TABLE public.storage_units ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated users" ON public.storage_units FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 2. bookings
CREATE TABLE IF NOT EXISTS public.bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id bigint REFERENCES public.storage_units(id),
    customer_name text,
    customer_email text,
    customer_mobile text,
    lease_start_date date,
    lease_end_date date,
    bond_amount numeric,
    monthly_rent numeric,
    docusign_link text,
    status text DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Active', 'Ending', 'Completed', 'Rejected', 'Cancelled')),
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated users" ON public.bookings FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 3. call_analytics
CREATE TABLE IF NOT EXISTS public.call_analytics (
    call_id text PRIMARY KEY,
    agent_id text,
    call_status text,
    start_time timestamptz,
    end_time timestamptz,
    duration_seconds integer,
    caller_number text,
    agent_number text,
    recording_url text,
    transcript_summary text,
    transcript_full text,
    call_sentiment text,
    user_sentiment text,
    agent_sentiment text,
    call_successful boolean,
    handoff_success boolean,
    lead_quality_score text,
    csat_score text,
    competitor_mention text,
    requested_move_in_window text,
    cost_credits numeric,
    llm_charge numeric,
    call_charge numeric,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE public.call_analytics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated users" ON public.call_analytics FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 4. knowledge_base
CREATE TABLE IF NOT EXISTS public.knowledge_base (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question text NOT NULL,
    answer text NOT NULL,
    category text,
    tags text[],
    is_public boolean DEFAULT false,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);
ALTER TABLE public.knowledge_base ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated users" ON public.knowledge_base FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 5. australian_public_holidays
CREATE TABLE IF NOT EXISTS public.australian_public_holidays (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_name text NOT NULL,
    holiday_date date NOT NULL,
    holiday_year integer,
    holiday_day text,
    state_code text,
    is_national boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE public.australian_public_holidays ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated users" ON public.australian_public_holidays FOR ALL TO authenticated USING (true) WITH CHECK (true);
