// Australian Suburb/Postcode data for autocomplete
// Source: Matthew Proctor's Australian Postcodes (Free dataset)
// For privacy focused on Tasmania but includes all Australian states

export interface SuburbData {
  suburb: string;
  postcode: string;
  state: string;
}

// Tasmania suburbs - most relevant for this app
// The full Australian dataset can be loaded from external JSON if needed
export const tasmaniaSuburbs: SuburbData[] = [
  { suburb: "Ulverstone", postcode: "7315", state: "TAS" },
  { suburb: "Penguin", postcode: "7316", state: "TAS" },
  { suburb: "Burnie", postcode: "7320", state: "TAS" },
  { suburb: "Devonport", postcode: "7310", state: "TAS" },
  { suburb: "Launceston", postcode: "7250", state: "TAS" },
  { suburb: "Hobart", postcode: "7000", state: "TAS" },
  { suburb: "Glenorchy", postcode: "7010", state: "TAS" },
  { suburb: "Kingston", postcode: "7050", state: "TAS" },
  { suburb: "Sandy Bay", postcode: "7005", state: "TAS" },
  { suburb: "Moonah", postcode: "7009", state: "TAS" },
  { suburb: "New Town", postcode: "7008", state: "TAS" },
  { suburb: "North Hobart", postcode: "7000", state: "TAS" },
  { suburb: "South Hobart", postcode: "7004", state: "TAS" },
  { suburb: "West Hobart", postcode: "7000", state: "TAS" },
  { suburb: "Battery Point", postcode: "7004", state: "TAS" },
  { suburb: "Bellerive", postcode: "7018", state: "TAS" },
  { suburb: "Howrah", postcode: "7018", state: "TAS" },
  { suburb: "Lindisfarne", postcode: "7015", state: "TAS" },
  { suburb: "Rosny", postcode: "7018", state: "TAS" },
  { suburb: "Clarence", postcode: "7170", state: "TAS" },
  { suburb: "Claremont", postcode: "7011", state: "TAS" },
  { suburb: "Austins Ferry", postcode: "7011", state: "TAS" },
  { suburb: "Granton", postcode: "7030", state: "TAS" },
  { suburb: "Brighton", postcode: "7030", state: "TAS" },
  { suburb: "Bridgewater", postcode: "7030", state: "TAS" },
  { suburb: "New Norfolk", postcode: "7140", state: "TAS" },
  { suburb: "Sorell", postcode: "7172", state: "TAS" },
  { suburb: "Richmond", postcode: "7025", state: "TAS" },
  { suburb: "Huonville", postcode: "7109", state: "TAS" },
  { suburb: "Geeveston", postcode: "7116", state: "TAS" },
  { suburb: "Dover", postcode: "7117", state: "TAS" },
  { suburb: "Cygnet", postcode: "7112", state: "TAS" },
  { suburb: "Woodbridge", postcode: "7162", state: "TAS" },
  { suburb: "Margate", postcode: "7054", state: "TAS" },
  { suburb: "Snug", postcode: "7054", state: "TAS" },
  { suburb: "Blackmans Bay", postcode: "7052", state: "TAS" },
  { suburb: "Taroona", postcode: "7053", state: "TAS" },
  { suburb: "Mount Nelson", postcode: "7007", state: "TAS" },
  { suburb: "Dynnyrne", postcode: "7005", state: "TAS" },
  { suburb: "Lenah Valley", postcode: "7008", state: "TAS" },
  { suburb: "Mount Stuart", postcode: "7000", state: "TAS" },
  { suburb: "South Launceston", postcode: "7249", state: "TAS" },
  { suburb: "East Launceston", postcode: "7250", state: "TAS" },
  { suburb: "West Launceston", postcode: "7250", state: "TAS" },
  { suburb: "Newstead", postcode: "7250", state: "TAS" },
  { suburb: "Kings Meadows", postcode: "7249", state: "TAS" },
  { suburb: "Prospect", postcode: "7250", state: "TAS" },
  { suburb: "Ravenswood", postcode: "7250", state: "TAS" },
  { suburb: "Mowbray", postcode: "7248", state: "TAS" },
  { suburb: "Newnham", postcode: "7248", state: "TAS" },
  { suburb: "Riverside", postcode: "7250", state: "TAS" },
  { suburb: "Trevallyn", postcode: "7250", state: "TAS" },
  { suburb: "Legana", postcode: "7277", state: "TAS" },
  { suburb: "Grindelwald", postcode: "7277", state: "TAS" },
  { suburb: "Hadspen", postcode: "7290", state: "TAS" },
  { suburb: "Carrick", postcode: "7291", state: "TAS" },
  { suburb: "Westbury", postcode: "7303", state: "TAS" },
  { suburb: "Deloraine", postcode: "7304", state: "TAS" },
  { suburb: "Longford", postcode: "7301", state: "TAS" },
  { suburb: "Perth", postcode: "7300", state: "TAS" },
  { suburb: "Evandale", postcode: "7212", state: "TAS" },
  { suburb: "Campbell Town", postcode: "7210", state: "TAS" },
  { suburb: "Ross", postcode: "7209", state: "TAS" },
  { suburb: "Oatlands", postcode: "7120", state: "TAS" },
  { suburb: "Bothwell", postcode: "7030", state: "TAS" },
  { suburb: "Hamilton", postcode: "7140", state: "TAS" },
  { suburb: "Ouse", postcode: "7140", state: "TAS" },
  { suburb: "Queenstown", postcode: "7467", state: "TAS" },
  { suburb: "Strahan", postcode: "7468", state: "TAS" },
  { suburb: "Zeehan", postcode: "7469", state: "TAS" },
  { suburb: "Rosebery", postcode: "7470", state: "TAS" },
  { suburb: "Tullah", postcode: "7321", state: "TAS" },
  { suburb: "Waratah", postcode: "7321", state: "TAS" },
  { suburb: "Somerset", postcode: "7322", state: "TAS" },
  { suburb: "Wynyard", postcode: "7325", state: "TAS" },
  { suburb: "Boat Harbour", postcode: "7321", state: "TAS" },
  { suburb: "Stanley", postcode: "7331", state: "TAS" },
  { suburb: "Smithton", postcode: "7330", state: "TAS" },
  { suburb: "Marrawah", postcode: "7330", state: "TAS" },
  { suburb: "Arthur River", postcode: "7330", state: "TAS" },
  { suburb: "Sheffield", postcode: "7306", state: "TAS" },
  { suburb: "Railton", postcode: "7305", state: "TAS" },
  { suburb: "Latrobe", postcode: "7307", state: "TAS" },
  { suburb: "Port Sorell", postcode: "7307", state: "TAS" },
  { suburb: "Shearwater", postcode: "7307", state: "TAS" },
  { suburb: "Turners Beach", postcode: "7315", state: "TAS" },
  { suburb: "Forth", postcode: "7310", state: "TAS" },
  { suburb: "Spreyton", postcode: "7310", state: "TAS" },
  { suburb: "East Devonport", postcode: "7310", state: "TAS" },
  { suburb: "Don", postcode: "7310", state: "TAS" },
  { suburb: "Miandetta", postcode: "7310", state: "TAS" },
  { suburb: "Quoiba", postcode: "7310", state: "TAS" },
  { suburb: "Stony Rise", postcode: "7310", state: "TAS" },
  { suburb: "Ambleside", postcode: "7310", state: "TAS" },
  { suburb: "Pardoe", postcode: "7310", state: "TAS" },
  { suburb: "West Ulverstone", postcode: "7315", state: "TAS" },
  { suburb: "Gawler", postcode: "7315", state: "TAS" },
  { suburb: "Leith", postcode: "7315", state: "TAS" },
  { suburb: "Gunns Plains", postcode: "7315", state: "TAS" },
  { suburb: "North Motton", postcode: "7315", state: "TAS" },
  { suburb: "South Riana", postcode: "7316", state: "TAS" },
  { suburb: "Riana", postcode: "7316", state: "TAS" },
  { suburb: "Cuprona", postcode: "7316", state: "TAS" },
  { suburb: "Sulphur Creek", postcode: "7316", state: "TAS" },
  { suburb: "Howth", postcode: "7316", state: "TAS" },
  { suburb: "West Pine", postcode: "7316", state: "TAS" },
  { suburb: "Heybridge", postcode: "7316", state: "TAS" },
  { suburb: "Camdale", postcode: "7320", state: "TAS" },
  { suburb: "Cooee", postcode: "7320", state: "TAS" },
  { suburb: "Brooklyn", postcode: "7320", state: "TAS" },
  { suburb: "Parklands", postcode: "7320", state: "TAS" },
  { suburb: "Shorewell Park", postcode: "7320", state: "TAS" },
  { suburb: "South Burnie", postcode: "7320", state: "TAS" },
  { suburb: "Montello", postcode: "7320", state: "TAS" },
  { suburb: "Acton", postcode: "7320", state: "TAS" },
  { suburb: "Upper Burnie", postcode: "7320", state: "TAS" },
  { suburb: "Emu Heights", postcode: "7320", state: "TAS" },
  { suburb: "Romaine", postcode: "7320", state: "TAS" },
  { suburb: "Havenview", postcode: "7320", state: "TAS" },
  { suburb: "Ocean Vista", postcode: "7320", state: "TAS" },
  { suburb: "Round Hill", postcode: "7320", state: "TAS" },
  { suburb: "Wivenhoe", postcode: "7320", state: "TAS" },
  { suburb: "Hillcrest", postcode: "7320", state: "TAS" },
  { suburb: "George Town", postcode: "7253", state: "TAS" },
  { suburb: "Beauty Point", postcode: "7270", state: "TAS" },
  { suburb: "Beaconsfield", postcode: "7270", state: "TAS" },
  { suburb: "Exeter", postcode: "7275", state: "TAS" },
  { suburb: "Gravelly Beach", postcode: "7276", state: "TAS" },
  { suburb: "Kayena", postcode: "7270", state: "TAS" },
  { suburb: "Bridport", postcode: "7262", state: "TAS" },
  { suburb: "Scottsdale", postcode: "7260", state: "TAS" },
  { suburb: "Derby", postcode: "7264", state: "TAS" },
  { suburb: "Winnaleah", postcode: "7265", state: "TAS" },
  { suburb: "Ringarooma", postcode: "7263", state: "TAS" },
  { suburb: "St Helens", postcode: "7216", state: "TAS" },
  { suburb: "Bicheno", postcode: "7215", state: "TAS" },
  { suburb: "Scamander", postcode: "7215", state: "TAS" },
  { suburb: "St Marys", postcode: "7215", state: "TAS" },
  { suburb: "Fingal", postcode: "7214", state: "TAS" },
  { suburb: "Avoca", postcode: "7213", state: "TAS" },
  { suburb: "Swansea", postcode: "7190", state: "TAS" },
  { suburb: "Coles Bay", postcode: "7215", state: "TAS" },
  { suburb: "Freycinet", postcode: "7215", state: "TAS" },
  { suburb: "Triabunna", postcode: "7190", state: "TAS" },
  { suburb: "Orford", postcode: "7190", state: "TAS" },
  { suburb: "Buckland", postcode: "7190", state: "TAS" },
  { suburb: "Dunalley", postcode: "7177", state: "TAS" },
  { suburb: "Eaglehawk Neck", postcode: "7179", state: "TAS" },
  { suburb: "Port Arthur", postcode: "7182", state: "TAS" },
  { suburb: "Nubeena", postcode: "7184", state: "TAS" },
  { suburb: "Koonya", postcode: "7187", state: "TAS" },
  { suburb: "Saltwater River", postcode: "7186", state: "TAS" },
  { suburb: "Premaydena", postcode: "7185", state: "TAS" },
  { suburb: "White Beach", postcode: "7184", state: "TAS" },
  { suburb: "Taranna", postcode: "7180", state: "TAS" },
  { suburb: "Murdunna", postcode: "7178", state: "TAS" },
  { suburb: "Dodges Ferry", postcode: "7173", state: "TAS" },
  { suburb: "Lewisham", postcode: "7173", state: "TAS" },
  { suburb: "Carlton", postcode: "7173", state: "TAS" },
  { suburb: "Primrose Sands", postcode: "7173", state: "TAS" },
  { suburb: "Seven Mile Beach", postcode: "7170", state: "TAS" },
  { suburb: "Cambridge", postcode: "7170", state: "TAS" },
  { suburb: "Cremorne", postcode: "7024", state: "TAS" },
  { suburb: "Clifton Beach", postcode: "7020", state: "TAS" },
  { suburb: "Lauderdale", postcode: "7021", state: "TAS" },
  { suburb: "South Arm", postcode: "7022", state: "TAS" },
  { suburb: "Opossum Bay", postcode: "7023", state: "TAS" },
  { suburb: "Rokeby", postcode: "7019", state: "TAS" },
  { suburb: "Oakdowns", postcode: "7019", state: "TAS" },
  { suburb: "Tranmere", postcode: "7018", state: "TAS" },
  { suburb: "Warrane", postcode: "7018", state: "TAS" },
  { suburb: "Montagu Bay", postcode: "7018", state: "TAS" },
  { suburb: "Mornington", postcode: "7018", state: "TAS" },
  { suburb: "Risdon Vale", postcode: "7016", state: "TAS" },
  { suburb: "Risdon", postcode: "7017", state: "TAS" },
  { suburb: "Old Beach", postcode: "7017", state: "TAS" },
  { suburb: "Otago", postcode: "7017", state: "TAS" },
  { suburb: "Geilston Bay", postcode: "7015", state: "TAS" },
  { suburb: "Montrose", postcode: "7010", state: "TAS" },
  { suburb: "Rosetta", postcode: "7010", state: "TAS" },
  { suburb: "Derwent Park", postcode: "7009", state: "TAS" },
  { suburb: "Lutana", postcode: "7009", state: "TAS" },
  { suburb: "Goodwood", postcode: "7010", state: "TAS" },
  { suburb: "Dowsing Point", postcode: "7010", state: "TAS" },
  { suburb: "Berriedale", postcode: "7011", state: "TAS" },
  { suburb: "Chigwell", postcode: "7011", state: "TAS" },
  { suburb: "Collinsvale", postcode: "7012", state: "TAS" },
  { suburb: "Glenlusk", postcode: "7012", state: "TAS" },
  { suburb: "Molesworth", postcode: "7140", state: "TAS" },
  { suburb: "Westerway", postcode: "7140", state: "TAS" },
  { suburb: "National Park", postcode: "7140", state: "TAS" },
  { suburb: "Maydena", postcode: "7140", state: "TAS" },
  { suburb: "Strathgordon", postcode: "7139", state: "TAS" },
  { suburb: "Bruny Island", postcode: "7150", state: "TAS" },
  { suburb: "Adventure Bay", postcode: "7150", state: "TAS" },
  { suburb: "Alonnah", postcode: "7150", state: "TAS" },
  { suburb: "Lunawanna", postcode: "7150", state: "TAS" },
  { suburb: "Dennes Point", postcode: "7150", state: "TAS" },
  { suburb: "Great Bay", postcode: "7150", state: "TAS" },
  { suburb: "Kettering", postcode: "7155", state: "TAS" },
  { suburb: "Middleton", postcode: "7163", state: "TAS" },
  { suburb: "Gordon", postcode: "7150", state: "TAS" },
  { suburb: "Franklin", postcode: "7113", state: "TAS" },
  { suburb: "Castle Forbes Bay", postcode: "7116", state: "TAS" },
  { suburb: "Police Point", postcode: "7116", state: "TAS" },
  { suburb: "Surges Bay", postcode: "7116", state: "TAS" },
  { suburb: "Lune River", postcode: "7109", state: "TAS" },
  { suburb: "Recherche", postcode: "7109", state: "TAS" },
  { suburb: "Catamaran", postcode: "7109", state: "TAS" },
  { suburb: "Southport", postcode: "7109", state: "TAS" },
  { suburb: "Cockle Creek", postcode: "7109", state: "TAS" },
  { suburb: "Flinders Island", postcode: "7255", state: "TAS" },
  { suburb: "Whitemark", postcode: "7255", state: "TAS" },
  { suburb: "Lady Barron", postcode: "7255", state: "TAS" },
  { suburb: "Emita", postcode: "7255", state: "TAS" },
  { suburb: "King Island", postcode: "7256", state: "TAS" },
  { suburb: "Currie", postcode: "7256", state: "TAS" },
  { suburb: "Grassy", postcode: "7256", state: "TAS" },
  { suburb: "Naracoopa", postcode: "7256", state: "TAS" },
  // Central Highlands / Great Lake area
  { suburb: "Miena", postcode: "7030", state: "TAS" },
  { suburb: "Liawenee", postcode: "7030", state: "TAS" },
  { suburb: "Arthurs Lake", postcode: "7030", state: "TAS" },
  { suburb: "Interlaken", postcode: "7030", state: "TAS" },
  { suburb: "Cramps Bay", postcode: "7030", state: "TAS" },
  { suburb: "Wilburville", postcode: "7030", state: "TAS" },
  { suburb: "Flintstone", postcode: "7030", state: "TAS" },
  { suburb: "Shannon", postcode: "7030", state: "TAS" },
  { suburb: "Steppes", postcode: "7030", state: "TAS" },
  { suburb: "Bothwell", postcode: "7030", state: "TAS" },
  { suburb: "Bronte Park", postcode: "7140", state: "TAS" },
  { suburb: "London Lakes", postcode: "7140", state: "TAS" },
  { suburb: "Ouse", postcode: "7140", state: "TAS" },
  { suburb: "Derwent Bridge", postcode: "7140", state: "TAS" },
  { suburb: "Tarraleah", postcode: "7140", state: "TAS" },
  { suburb: "Wayatinah", postcode: "7140", state: "TAS" },
  { suburb: "Breona", postcode: "7304", state: "TAS" },
  { suburb: "Reynolds Neck", postcode: "7304", state: "TAS" },
  { suburb: "Brandum", postcode: "7304", state: "TAS" },
  { suburb: "Doctors Point", postcode: "7304", state: "TAS" },
  { suburb: "Tods Corner", postcode: "7304", state: "TAS" },
];

// Common suburbs from other Australian states for cross-reference
export const otherStatesSuburbs: SuburbData[] = [
  // Victoria
  { suburb: "Melbourne", postcode: "3000", state: "VIC" },
  { suburb: "Geelong", postcode: "3220", state: "VIC" },
  { suburb: "Ballarat", postcode: "3350", state: "VIC" },
  { suburb: "Bendigo", postcode: "3550", state: "VIC" },
  // New South Wales
  { suburb: "Sydney", postcode: "2000", state: "NSW" },
  { suburb: "Newcastle", postcode: "2300", state: "NSW" },
  { suburb: "Wollongong", postcode: "2500", state: "NSW" },
  // Queensland
  { suburb: "Brisbane", postcode: "4000", state: "QLD" },
  { suburb: "Gold Coast", postcode: "4217", state: "QLD" },
  { suburb: "Cairns", postcode: "4870", state: "QLD" },
  // South Australia
  { suburb: "Adelaide", postcode: "5000", state: "SA" },
  // Western Australia
  { suburb: "Perth", postcode: "6000", state: "WA" },
  // Northern Territory
  { suburb: "Darwin", postcode: "0800", state: "NT" },
  // ACT
  { suburb: "Canberra", postcode: "2600", state: "ACT" },
];

// Combined dataset for autocomplete
export const allSuburbs: SuburbData[] = [
  ...tasmaniaSuburbs,
  ...otherStatesSuburbs,
];

// Helper to check if a suburb exists (case-insensitive)
export function isValidSuburb(suburbName: string): boolean {
  if (!suburbName) return false;
  const normalizedInput = suburbName.trim().toLowerCase();
  return allSuburbs.some((s) => s.suburb.toLowerCase() === normalizedInput);
}
